spring.application.name=hrm

# ========================
# SERVER
# ========================
server.port=${PORT:8080}
server.servlet.context-path=/api
# ========================
# DATABASE (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hrm}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:htt150704}
#
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA
# ========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========================
# JWT
# ========================
jwt.secret=${JWT_SECRET:1e5740c80d5e60667f238a1df88921fcba0eb84af91f768bdb6f191baf8564d7}
jwt.refresh-secret=${JWT_REFRESH_SECRET:cd690ab67433dd72f35a5ee1a2952404cdcaef2308e5d4a5cd5408ca580698a9}